### ISSUE TITLE
Should I use tools/vid2img_sthv2.py to extract frames of JESTER dataset?

### ISSUE THREAD

**Issue by lukysummer** [zhang-can/PAN-PyTorch#2]
First of all, thank you for a great paper! :)

I am working on implementing your paper on **20BN-JESTER hand recognition dataset**, and had a few questions.

1. To extract frames of Jester Dataset, should I use (refer to):

-  this repo's tools/vid2img_sthv2.py  OR
- "dump_frame" function in TSN repo (https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/build_of.py)

2. Do you happen to have any pre-trained model checkpoints for Jester dataset?

3. Could I ask about **how long it took** to train different models (resnet50, resnet101, PAN_lite, PAN_full) with Jester dataset?

Thank you so much for your help.

Lucrece

**Comment by zhang-can** [comment]
Hi @lukysummer ,

Thanks for your interest in our work :) And sorry for the late reply! 

1. Both scripts are fine, just make sure that you can generate file lists like tsn-style (Please see [data-preparation](https://github.com/zhang-can/PAN-PyTorch#data-preparation) Step 2):

```
video_frame_folder 100 10
video_2_frame_folder 150 31
...
```

2. Sure, I just saw your email and will send you the checkpoints. More models will be publicly available when the paper is accepted.

3. We use 8 NVIDIA 2080 GPUs. For PAN_lite-resnet50, it takes about 20 hours. And for PAN_full-resnet50, it takes about 30 hours. Note that this time may vary greatly due to the disk I/O speed, CPU, GPU, etc.

If you have any other questions, feel free to post here!

Best wishes,
Can
